site_name: leitwerk
repo_name: leitwerk
repo_url: https://github.com/phantomsc2/leitwerk

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
          options:
            docstring_style: google
            show_root_heading: true
            show_root_full_path: false
            show_source: false
            separate_signature: true

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Overview: index.md
  - Quickstart: quickstart.md
  - Integration Guide: integration.md
  - API Reference: reference/api.md
  - FAQ: faq.md
